### PR TITLE
Localization [tr-TR]

### PR DESCRIPTION
**Pull request by ghost**
I couldn't create folders like the ones in the repo. I barely know how to use GitHub, it just adds slashes instead of creating the folder. Idk if this works, lol.

### CODE REVIEW

**Comment by regularentropy** [comment]
Hi once again!

Maybe it will be better for me to create a proper directory structure, what do you think ?

**Comment by ghost** [comment]
> Hi once again!
> 
> Maybe it will be better for me to create a proper directory structure, what do you think ?

idk man you probably know the answer better than me :D
If it is going to make things easier, maybe you should

**Comment by regularentropy** [comment]
Looks like it got merged, so I'm closing this PR.

**Comment by Ryosuke-Asano** [comment]
https://github.com/Floorp-Projects/l10n-central/commit/2fedb5e3a3005aa005bfeaa6152b33180b210511

**Pull request closed without merging**
